/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppRouteImport } from './routes/app'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAtsResumeGuideRouteImport } from './routes/_site/ats-resume-guide'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteLoginRouteImport } from './routes/_site/login'
import { Route as SitePricingRouteImport } from './routes/_site/pricing'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteRefundPolicyRouteImport } from './routes/_site/refund-policy'
import { Route as SiteShippingRouteImport } from './routes/_site/shipping'
import { Route as SiteSignupRouteImport } from './routes/_site/signup'
import { Route as SiteTemplatesRouteImport } from './routes/_site/templates'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as ApiCashfreeWebhookRouteImport } from './routes/api/cashfree/webhook'
import { Route as AppResumeIdRouteImport } from './routes/app/resume.$id'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAtsResumeGuideRoute = SiteAtsResumeGuideRouteImport.update({
  id: '/ats-resume-guide',
  path: '/ats-resume-guide',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLoginRoute = SiteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRefundPolicyRoute = SiteRefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShippingRoute = SiteShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSignupRoute = SiteSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTemplatesRoute = SiteTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const ApiCashfreeWebhookRoute = ApiCashfreeWebhookRouteImport.update({
  id: '/api/cashfree/webhook',
  path: '/api/cashfree/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResumeIdRoute = AppResumeIdRouteImport.update({
  id: '/resume/$id',
  path: '/resume/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ats-resume-guide': typeof SiteAtsResumeGuideRoute
  '/contact': typeof SiteContactRoute
  '/login': typeof SiteLoginRoute
  '/pricing': typeof SitePricingRoute
  '/privacy': typeof SitePrivacyRoute
  '/refund-policy': typeof SiteRefundPolicyRoute
  '/shipping': typeof SiteShippingRoute
  '/signup': typeof SiteSignupRoute
  '/templates': typeof SiteTemplatesRoute
  '/terms': typeof SiteTermsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/': typeof AppIndexRoute
  '/api/cashfree/webhook': typeof ApiCashfreeWebhookRoute
  '/app/resume/$id': typeof AppResumeIdRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ats-resume-guide': typeof SiteAtsResumeGuideRoute
  '/contact': typeof SiteContactRoute
  '/login': typeof SiteLoginRoute
  '/pricing': typeof SitePricingRoute
  '/privacy': typeof SitePrivacyRoute
  '/refund-policy': typeof SiteRefundPolicyRoute
  '/shipping': typeof SiteShippingRoute
  '/signup': typeof SiteSignupRoute
  '/templates': typeof SiteTemplatesRoute
  '/terms': typeof SiteTermsRoute
  '/app/billing': typeof AppBillingRoute
  '/': typeof SiteIndexRoute
  '/app': typeof AppIndexRoute
  '/api/cashfree/webhook': typeof ApiCashfreeWebhookRoute
  '/app/resume/$id': typeof AppResumeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/ats-resume-guide': typeof SiteAtsResumeGuideRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/login': typeof SiteLoginRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/refund-policy': typeof SiteRefundPolicyRoute
  '/_site/shipping': typeof SiteShippingRoute
  '/_site/signup': typeof SiteSignupRoute
  '/_site/templates': typeof SiteTemplatesRoute
  '/_site/terms': typeof SiteTermsRoute
  '/app/billing': typeof AppBillingRoute
  '/_site/': typeof SiteIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/cashfree/webhook': typeof ApiCashfreeWebhookRoute
  '/app/resume/$id': typeof AppResumeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sitemap.xml'
    | '/ats-resume-guide'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/shipping'
    | '/signup'
    | '/templates'
    | '/terms'
    | '/app/billing'
    | '/app/'
    | '/api/cashfree/webhook'
    | '/app/resume/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/ats-resume-guide'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/shipping'
    | '/signup'
    | '/templates'
    | '/terms'
    | '/app/billing'
    | '/'
    | '/app'
    | '/api/cashfree/webhook'
    | '/app/resume/$id'
  id:
    | '__root__'
    | '/_site'
    | '/app'
    | '/sitemap.xml'
    | '/_site/ats-resume-guide'
    | '/_site/contact'
    | '/_site/login'
    | '/_site/pricing'
    | '/_site/privacy'
    | '/_site/refund-policy'
    | '/_site/shipping'
    | '/_site/signup'
    | '/_site/templates'
    | '/_site/terms'
    | '/app/billing'
    | '/_site/'
    | '/app/'
    | '/api/cashfree/webhook'
    | '/app/resume/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCashfreeWebhookRoute: typeof ApiCashfreeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ats-resume-guide': {
      id: '/_site/ats-resume-guide'
      path: '/ats-resume-guide'
      fullPath: '/ats-resume-guide'
      preLoaderRoute: typeof SiteAtsResumeGuideRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/login': {
      id: '/_site/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteLoginRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/refund-policy': {
      id: '/_site/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof SiteRefundPolicyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shipping': {
      id: '/_site/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof SiteShippingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/signup': {
      id: '/_site/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SiteSignupRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/templates': {
      id: '/_site/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof SiteTemplatesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/cashfree/webhook': {
      id: '/api/cashfree/webhook'
      path: '/api/cashfree/webhook'
      fullPath: '/api/cashfree/webhook'
      preLoaderRoute: typeof ApiCashfreeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/resume/$id': {
      id: '/app/resume/$id'
      path: '/resume/$id'
      fullPath: '/app/resume/$id'
      preLoaderRoute: typeof AppResumeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAtsResumeGuideRoute: typeof SiteAtsResumeGuideRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteLoginRoute: typeof SiteLoginRoute
  SitePricingRoute: typeof SitePricingRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteRefundPolicyRoute: typeof SiteRefundPolicyRoute
  SiteShippingRoute: typeof SiteShippingRoute
  SiteSignupRoute: typeof SiteSignupRoute
  SiteTemplatesRoute: typeof SiteTemplatesRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAtsResumeGuideRoute: SiteAtsResumeGuideRoute,
  SiteContactRoute: SiteContactRoute,
  SiteLoginRoute: SiteLoginRoute,
  SitePricingRoute: SitePricingRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteRefundPolicyRoute: SiteRefundPolicyRoute,
  SiteShippingRoute: SiteShippingRoute,
  SiteSignupRoute: SiteSignupRoute,
  SiteTemplatesRoute: SiteTemplatesRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppResumeIdRoute: typeof AppResumeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppIndexRoute: AppIndexRoute,
  AppResumeIdRoute: AppResumeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCashfreeWebhookRoute: ApiCashfreeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
